site_name: 'Blog @snoopyx21'
site_dir: /var/www/mkdocs
site_author: 'Constantin DIvriotis'
site_url: https://ganymede.blog/
site_description: >-
  Constantin Divriotis | Playground
repo_url: https://github.com/snoopyx21/ganymede
theme:
  name: material
  features:
    - navigation.footer


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - My Cookbooks:
    - AIX Cookbook: guide/aix.md
    - Linux Cookbook: guide/linux.md


extra:
  social:
    - icon: simple/github
      link: https://github.com/snoopyx21


copyright: Copyright &copy; 2025 Constantin Divriotis. All rights reserved.