site_name: 'Blog @snoopyx21'
site_dir: /var/www/mkdocs
site_author: 'Constantin Divriotis'
site_url: https://ganymede.blog/
site_description: >-
  Constantin Divriotis | Playground
repo_url: https://github.com/snoopyx21/ganymede
theme:
  name: material
  logo: ./assets/logo-snoopy.png
  #favicon: ./assets/favicon.ico
  features:
    - navigation.footer
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

nav:
  - Home: index.md
  - AIX Cookbook:
    - AIX Concepts: guides/aix/general.md
  - Linux Cookbook: 
    - Linux Concepts: guides/linux/general.md


extra:
  social:
    - icon: simple/github
      link: https://github.com/snoopyx21


copyright: Copyright &copy; 2025 Constantin Divriotis | Powered by GNU GPLv3